_features_modelling=[
"browse_count_journey_PD_07days",
"add_to_basket_journey_PD_07days",
"browse_count_OJ_from_first_Date",
"catalog_page_view_journey_PD_14days",
"Days_since_last_addtobasket_journey",
"Days_since_last_search_journey",
"Days_since_last_search_OJ",
"derived_gender_M",
"detail_page_view_OJ_from_first_Date",
"detail_page_view_journey_PD_07days",
"distinct_count_PD_07days_journey",
"distinct_count_from_first_Date_journey",
"distinct_count_from_first_Date_OJ",
"Distinct_Days_by_Days_first_search_journey",
"Distinct_Days_by_Days_first_search_OJ",
"dtime_on_category_by_avg_dtime_journey",
"dwell_time_seconds_journey_PD_07days",
"hit_per_day_site",
"number_of_desktop_visit_journey_PD_07days",
"page_visit_count_distinct",
"product_browse_all_count_journey_PD_07days",
"product_browse_all_count_OJ_from_first_Date",
"product_Browse_count_distinct_journey_PD_07days",
"product_Browse_count_distinct_OJ_from_first_Date",
"searches_on_category_by_avg_searches_OJ",
"total_count_from_first_Date_journey",
"total_count_PD_28days_OJ",
"MARITAL_STATUS_Engaged Soon"]

_features_aggregation=['guid_key', 'date_key', 'browse_count_wedding','browse_count_dj', 'browse_count_oj','browse_month_first_date_weddding', 'browse_month_last_date_wedding','browse_year_first_date_Wedding', 'browse_year_last_date_Wedding','browse_month_first_oj', 'browse_month_last_oj', 'browse_year_first_oj','browse_year_last_oj', 'browse_month_first_dj', 'browse_month_last_dj','browse_year_first_dj', 'browse_year_last_dj','product_Browse_count_distinct_wedding','product_Browse_count_distinct_dj', 'product_Browse_count_distinct_oj','product_browse_all_count_wedding', 'product_browse_all_count_dj','product_browse_all_count_oj', 'detail_page_view_wedding','detail_page_view_oj', 'detail_page_view_dj','catalog_page_view_wedding', 'catalog_page_view_oj','catalog_page_view_dj', 'derived_gender', 'dwell_time_seconds_oj','dwell_time_seconds_dj', 'dwell_time_seconds_wedding','dwell_time_seconds_site', 'hit_per_day_site', 'MARITAL_STATUS','number_of_desktop_visit_dj', 'number_of_desktop_visit_oj','number_of_desktop_visit_wedding', 'number_of_mobile_visits_dj','number_of_mobile_visits_oj', 'number_of_mobile_visits_wedding','number_of_webchats', 'page_visit_count_distinct','primary_currency_code', 'showroom_page_visit','search_count_number_wedding', 'search_count_number_dj','search_count_number_oj', 'review_count_number_dj','review_count_number_wedding', 'review_count_number_oj','education_page_count_num_wedding', 'education_page_count_num_oj','education_page_count_num_dj', 'add_to_basket_dj','add_to_basket_wedding', 'add_to_basket_oj', 'product_array_all_dj','product_array_all_oj', 'product_array_all_wedding','previous_orders_flag', 'purchase_flag_oj', 'purchase_flag_dj','purchase_flag_wedding']